{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "execution_count": 1,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "KOJ8SxY-Ar-k",
        "outputId": "a5676f25-a8d2-4331-fb6e-5569ac279ac6"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\n",
            "======================================\n",
            "              TO-DO LIST\n",
            "======================================\n",
            "1. Add Task\n",
            "2. View Tasks\n",
            "3. Complete Task\n",
            "4. Delete Task\n",
            "5. Exit\n",
            "======================================\n",
            "Enter your choice (1-5): 1\n",
            "\n",
            "========== ADD TASK ==========\n",
            "Enter your task: Complete Python assignment\n",
            "Task added successfully!\n",
            "\n",
            "======================================\n",
            "              TO-DO LIST\n",
            "======================================\n",
            "1. Add Task\n",
            "2. View Tasks\n",
            "3. Complete Task\n",
            "4. Delete Task\n",
            "5. Exit\n",
            "======================================\n",
            "Enter your choice (1-5): 5\n",
            "\n",
            "Thank you for using To-Do List!\n"
          ]
        }
      ],
      "source": [
        "# ============================================================\n",
        "#                    TO-DO LIST\n",
        "# ============================================================\n",
        "\n",
        "tasks = []\n",
        "\n",
        "\n",
        "# ------------------------------------------------------------\n",
        "# ADD TASK\n",
        "# ------------------------------------------------------------\n",
        "def add_task():\n",
        "    print(\"\\n========== ADD TASK ==========\")\n",
        "\n",
        "    task = input(\"Enter your task: \").strip()\n",
        "\n",
        "    if task == \"\":\n",
        "        print(\"Task cannot be empty!\")\n",
        "        return\n",
        "\n",
        "    tasks.append({\n",
        "        \"task\": task,\n",
        "        \"completed\": False\n",
        "    })\n",
        "\n",
        "    print(\"Task added successfully!\")\n",
        "\n",
        "\n",
        "# ------------------------------------------------------------\n",
        "# VIEW TASKS\n",
        "# ------------------------------------------------------------\n",
        "def view_tasks():\n",
        "    print(\"\\n========== YOUR TASKS ==========\")\n",
        "\n",
        "    if len(tasks) == 0:\n",
        "        print(\"No tasks available.\")\n",
        "        return\n",
        "\n",
        "    for i, item in enumerate(tasks, start=1):\n",
        "\n",
        "        if item[\"completed\"]:\n",
        "            status = \"Completed\"\n",
        "        else:\n",
        "            status = \"Pending\"\n",
        "\n",
        "        print(f\"{i}. {item['task']} - {status}\")\n",
        "\n",
        "\n",
        "# ------------------------------------------------------------\n",
        "# COMPLETE TASK\n",
        "# ------------------------------------------------------------\n",
        "def complete_task():\n",
        "    print(\"\\n========== COMPLETE TASK ==========\")\n",
        "\n",
        "    if len(tasks) == 0:\n",
        "        print(\"No tasks available.\")\n",
        "        return\n",
        "\n",
        "    view_tasks()\n",
        "\n",
        "    try:\n",
        "        task_number = int(input(\"Enter task number to complete: \"))\n",
        "    except ValueError:\n",
        "        print(\"Please enter a valid number!\")\n",
        "        return\n",
        "\n",
        "    if task_number < 1 or task_number > len(tasks):\n",
        "        print(\"Invalid task number!\")\n",
        "        return\n",
        "\n",
        "    tasks[task_number - 1][\"completed\"] = True\n",
        "\n",
        "    print(\"Task marked as completed!\")\n",
        "\n",
        "\n",
        "# ------------------------------------------------------------\n",
        "# DELETE TASK\n",
        "# ------------------------------------------------------------\n",
        "def delete_task():\n",
        "    print(\"\\n========== DELETE TASK ==========\")\n",
        "\n",
        "    if len(tasks) == 0:\n",
        "        print(\"No tasks available.\")\n",
        "        return\n",
        "\n",
        "    view_tasks()\n",
        "\n",
        "    try:\n",
        "        task_number = int(input(\"Enter task number to delete: \"))\n",
        "    except ValueError:\n",
        "        print(\"Please enter a valid number!\")\n",
        "        return\n",
        "\n",
        "    if task_number < 1 or task_number > len(tasks):\n",
        "        print(\"Invalid task number!\")\n",
        "        return\n",
        "\n",
        "    deleted_task = tasks.pop(task_number - 1)\n",
        "\n",
        "    print(\"Task deleted successfully!\")\n",
        "    print(\"Deleted task:\", deleted_task[\"task\"])\n",
        "\n",
        "\n",
        "# ------------------------------------------------------------\n",
        "# MAIN MENU\n",
        "# ------------------------------------------------------------\n",
        "def main():\n",
        "\n",
        "    while True:\n",
        "\n",
        "        print(\"\\n======================================\")\n",
        "        print(\"              TO-DO LIST\")\n",
        "        print(\"======================================\")\n",
        "        print(\"1. Add Task\")\n",
        "        print(\"2. View Tasks\")\n",
        "        print(\"3. Complete Task\")\n",
        "        print(\"4. Delete Task\")\n",
        "        print(\"5. Exit\")\n",
        "        print(\"======================================\")\n",
        "\n",
        "        choice = input(\"Enter your choice (1-5): \").strip()\n",
        "\n",
        "        if choice == \"1\":\n",
        "            add_task()\n",
        "\n",
        "        elif choice == \"2\":\n",
        "            view_tasks()\n",
        "\n",
        "        elif choice == \"3\":\n",
        "            complete_task()\n",
        "\n",
        "        elif choice == \"4\":\n",
        "            delete_task()\n",
        "\n",
        "        elif choice == \"5\":\n",
        "            print(\"\\nThank you for using To-Do List!\")\n",
        "            break\n",
        "\n",
        "        else:\n",
        "            print(\"Invalid choice! Please enter a number from 1 to 5.\")\n",
        "\n",
        "\n",
        "# ------------------------------------------------------------\n",
        "# START PROGRAM\n",
        "# ------------------------------------------------------------\n",
        "\n",
        "main()"
      ]
    }
  ]
}
