{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "execution_count": 1,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "9VAgjgn4Bnfu",
        "outputId": "c80b02ad-4e24-43ea-9ddd-798eea2e9bbe"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "==============================================\n",
            "                QUIZ GAME\n",
            "==============================================\n",
            "Enter your name: Raksha\n",
            "\n",
            "Hello, Raksha!\n",
            "Answer each question by entering A, B, C, or D.\n",
            "==============================================\n",
            "\n",
            "1. What is the capital of India?\n",
            "A. Mumbai\n",
            "B. New Delhi\n",
            "C. Kolkata\n",
            "D. Chennai\n",
            "Enter your answer: b\n",
            "Correct!\n",
            "\n",
            "2. Which language is used for Python programming?\n",
            "A. Python\n",
            "B. HTML\n",
            "C. CSS\n",
            "D. SQL\n",
            "Enter your answer: a\n",
            "Correct!\n",
            "\n",
            "3. How many days are there in a week?\n",
            "A. 5\n",
            "B. 6\n",
            "C. 7\n",
            "D. 8\n",
            "Enter your answer: c\n",
            "Correct!\n",
            "\n",
            "4. Which planet is known as the Red Planet?\n",
            "A. Earth\n",
            "B. Mars\n",
            "C. Jupiter\n",
            "D. Venus\n",
            "Enter your answer: b\n",
            "Correct!\n",
            "\n",
            "5. What is 10 + 5?\n",
            "A. 12\n",
            "B. 15\n",
            "C. 20\n",
            "D. 25\n",
            "Enter your answer: b\n",
            "Correct!\n",
            "\n",
            "6. Which device is used to enter text into a computer?\n",
            "A. Monitor\n",
            "B. Keyboard\n",
            "C. Speaker\n",
            "D. Printer\n",
            "Enter your answer: b\n",
            "Correct!\n",
            "\n",
            "7. Which is the largest ocean?\n",
            "A. Indian Ocean\n",
            "B. Atlantic Ocean\n",
            "C. Pacific Ocean\n",
            "D. Arctic Ocean\n",
            "Enter your answer: c\n",
            "Correct!\n",
            "\n",
            "8. What does CPU stand for?\n",
            "A. Central Processing Unit\n",
            "B. Computer Personal Unit\n",
            "C. Central Program Utility\n",
            "D. Computer Processing Utility\n",
            "Enter your answer: a\n",
            "Correct!\n",
            "\n",
            "9. Which number is a prime number?\n",
            "A. 4\n",
            "B. 6\n",
            "C. 9\n",
            "D. 7\n",
            "Enter your answer: d\n",
            "Correct!\n",
            "\n",
            "10. Which symbol is used for comments in Python?\n",
            "A. //\n",
            "B. #\n",
            "C. /* */\n",
            "D. <!-- -->\n",
            "Enter your answer: a\n",
            "Wrong!\n",
            "Correct answer: B\n",
            "\n",
            "==============================================\n",
            "                QUIZ RESULT\n",
            "==============================================\n",
            "Player: Raksha\n",
            "Total Questions: 10\n",
            "Correct Answers: 9\n",
            "Wrong Answers: 1\n",
            "Score: 9 / 10\n",
            "Percentage: 90.0 %\n",
            "Result: Excellent! 🎉\n",
            "==============================================\n",
            "          Thank you for playing!\n",
            "==============================================\n"
          ]
        }
      ],
      "source": [
        "# ============================================================\n",
        "#                    QUIZ GAME\n",
        "# ============================================================\n",
        "\n",
        "questions = [\n",
        "    {\n",
        "        \"question\": \"1. What is the capital of India?\",\n",
        "        \"options\": [\"A. Mumbai\", \"B. New Delhi\", \"C. Kolkata\", \"D. Chennai\"],\n",
        "        \"answer\": \"B\"\n",
        "    },\n",
        "    {\n",
        "        \"question\": \"2. Which language is used for Python programming?\",\n",
        "        \"options\": [\"A. Python\", \"B. HTML\", \"C. CSS\", \"D. SQL\"],\n",
        "        \"answer\": \"A\"\n",
        "    },\n",
        "    {\n",
        "        \"question\": \"3. How many days are there in a week?\",\n",
        "        \"options\": [\"A. 5\", \"B. 6\", \"C. 7\", \"D. 8\"],\n",
        "        \"answer\": \"C\"\n",
        "    },\n",
        "    {\n",
        "        \"question\": \"4. Which planet is known as the Red Planet?\",\n",
        "        \"options\": [\"A. Earth\", \"B. Mars\", \"C. Jupiter\", \"D. Venus\"],\n",
        "        \"answer\": \"B\"\n",
        "    },\n",
        "    {\n",
        "        \"question\": \"5. What is 10 + 5?\",\n",
        "        \"options\": [\"A. 12\", \"B. 15\", \"C. 20\", \"D. 25\"],\n",
        "        \"answer\": \"B\"\n",
        "    },\n",
        "    {\n",
        "        \"question\": \"6. Which device is used to enter text into a computer?\",\n",
        "        \"options\": [\"A. Monitor\", \"B. Keyboard\", \"C. Speaker\", \"D. Printer\"],\n",
        "        \"answer\": \"B\"\n",
        "    },\n",
        "    {\n",
        "        \"question\": \"7. Which is the largest ocean?\",\n",
        "        \"options\": [\"A. Indian Ocean\", \"B. Atlantic Ocean\", \"C. Pacific Ocean\", \"D. Arctic Ocean\"],\n",
        "        \"answer\": \"C\"\n",
        "    },\n",
        "    {\n",
        "        \"question\": \"8. What does CPU stand for?\",\n",
        "        \"options\": [\n",
        "            \"A. Central Processing Unit\",\n",
        "            \"B. Computer Personal Unit\",\n",
        "            \"C. Central Program Utility\",\n",
        "            \"D. Computer Processing Utility\"\n",
        "        ],\n",
        "        \"answer\": \"A\"\n",
        "    },\n",
        "    {\n",
        "        \"question\": \"9. Which number is a prime number?\",\n",
        "        \"options\": [\"A. 4\", \"B. 6\", \"C. 9\", \"D. 7\"],\n",
        "        \"answer\": \"D\"\n",
        "    },\n",
        "    {\n",
        "        \"question\": \"10. Which symbol is used for comments in Python?\",\n",
        "        \"options\": [\"A. //\", \"B. #\", \"C. /* */\", \"D. <!-- -->\"],\n",
        "        \"answer\": \"B\"\n",
        "    }\n",
        "]\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# START QUIZ\n",
        "# ============================================================\n",
        "\n",
        "print(\"==============================================\")\n",
        "print(\"                QUIZ GAME\")\n",
        "print(\"==============================================\")\n",
        "\n",
        "name = input(\"Enter your name: \").strip()\n",
        "\n",
        "if name == \"\":\n",
        "    name = \"Player\"\n",
        "\n",
        "print(\"\\nHello,\", name + \"!\")\n",
        "print(\"Answer each question by entering A, B, C, or D.\")\n",
        "print(\"==============================================\")\n",
        "\n",
        "score = 0\n",
        "\n",
        "# Ask questions\n",
        "for item in questions:\n",
        "\n",
        "    print(\"\\n\" + item[\"question\"])\n",
        "\n",
        "    for option in item[\"options\"]:\n",
        "        print(option)\n",
        "\n",
        "    while True:\n",
        "        user_answer = input(\"Enter your answer: \").strip().upper()\n",
        "\n",
        "        if user_answer in [\"A\", \"B\", \"C\", \"D\"]:\n",
        "            break\n",
        "        else:\n",
        "            print(\"Invalid answer! Please enter A, B, C, or D.\")\n",
        "\n",
        "    if user_answer == item[\"answer\"]:\n",
        "        print(\"Correct!\")\n",
        "        score += 1\n",
        "    else:\n",
        "        print(\"Wrong!\")\n",
        "        print(\"Correct answer:\", item[\"answer\"])\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# FINAL RESULT\n",
        "# ============================================================\n",
        "\n",
        "total_questions = len(questions)\n",
        "percentage = (score / total_questions) * 100\n",
        "\n",
        "print(\"\\n==============================================\")\n",
        "print(\"                QUIZ RESULT\")\n",
        "print(\"==============================================\")\n",
        "\n",
        "print(\"Player:\", name)\n",
        "print(\"Total Questions:\", total_questions)\n",
        "print(\"Correct Answers:\", score)\n",
        "print(\"Wrong Answers:\", total_questions - score)\n",
        "print(\"Score:\", score, \"/\", total_questions)\n",
        "print(\"Percentage:\", round(percentage, 2), \"%\")\n",
        "\n",
        "if percentage >= 80:\n",
        "    print(\"Result: Excellent! 🎉\")\n",
        "elif percentage >= 60:\n",
        "    print(\"Result: Very Good! 👍\")\n",
        "elif percentage >= 40:\n",
        "    print(\"Result: Good! Keep practicing.\")\n",
        "else:\n",
        "    print(\"Result: Keep learning and try again!\")\n",
        "\n",
        "print(\"==============================================\")\n",
        "print(\"          Thank you for playing!\")\n",
        "print(\"==============================================\")"
      ]
    }
  ]
}
