{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "execution_count": 1,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "XpJRdEatO2S4",
        "outputId": "714156a4-69c6-49e4-e271-6a89d3f730b8"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\n",
            "\n",
            "=================================================================\n",
            "             🚦 TRAFFIC VIOLATION ANALYZER\n",
            "=================================================================\n",
            "1. 📋 Display All Violations\n",
            "2. ➕ Add New Violation\n",
            "3. 🔎 Search Vehicle\n",
            "4. 📊 Violation Statistics\n",
            "5. 📍 Location Analysis\n",
            "6. ⚠️ High-Risk Analysis\n",
            "7. 🚗 Vehicle Analysis\n",
            "8. 📈 Dashboard\n",
            "9. 🚪 Exit\n",
            "=================================================================\n",
            "Enter your choice (1-9): 1\n",
            "\n",
            "================================================================================\n",
            "                  ALL TRAFFIC VIOLATIONS\n",
            "================================================================================\n",
            "\n",
            "Record 1\n",
            "--------------------------------------------------\n",
            "Vehicle Number : DL01AB1234\n",
            "Location       : Delhi\n",
            "Violation      : No Helmet\n",
            "Date           : 01-08-2026\n",
            "Fine           : ₹ 1000\n",
            "\n",
            "Record 2\n",
            "--------------------------------------------------\n",
            "Vehicle Number : DL02CD5678\n",
            "Location       : Noida\n",
            "Violation      : Red Light Jump\n",
            "Date           : 02-08-2026\n",
            "Fine           : ₹ 5000\n",
            "\n",
            "Record 3\n",
            "--------------------------------------------------\n",
            "Vehicle Number : DL03EF9012\n",
            "Location       : Delhi\n",
            "Violation      : Overspeeding\n",
            "Date           : 03-08-2026\n",
            "Fine           : ₹ 2000\n",
            "\n",
            "Record 4\n",
            "--------------------------------------------------\n",
            "Vehicle Number : UP16GH3456\n",
            "Location       : Noida\n",
            "Violation      : No Seat Belt\n",
            "Date           : 04-08-2026\n",
            "Fine           : ₹ 1000\n",
            "\n",
            "Record 5\n",
            "--------------------------------------------------\n",
            "Vehicle Number : DL04IJ7890\n",
            "Location       : Delhi\n",
            "Violation      : Overspeeding\n",
            "Date           : 05-08-2026\n",
            "Fine           : ₹ 2000\n",
            "\n",
            "Record 6\n",
            "--------------------------------------------------\n",
            "Vehicle Number : HR26KL1122\n",
            "Location       : Gurugram\n",
            "Violation      : Drunk Driving\n",
            "Date           : 06-08-2026\n",
            "Fine           : ₹ 10000\n",
            "\n",
            "Record 7\n",
            "--------------------------------------------------\n",
            "Vehicle Number : DL05MN3344\n",
            "Location       : Delhi\n",
            "Violation      : No Helmet\n",
            "Date           : 07-08-2026\n",
            "Fine           : ₹ 1000\n",
            "\n",
            "Record 8\n",
            "--------------------------------------------------\n",
            "Vehicle Number : UP14OP5566\n",
            "Location       : Noida\n",
            "Violation      : Red Light Jump\n",
            "Date           : 08-08-2026\n",
            "Fine           : ₹ 5000\n",
            "================================================================================\n",
            "\n",
            "\n",
            "=================================================================\n",
            "             🚦 TRAFFIC VIOLATION ANALYZER\n",
            "=================================================================\n",
            "1. 📋 Display All Violations\n",
            "2. ➕ Add New Violation\n",
            "3. 🔎 Search Vehicle\n",
            "4. 📊 Violation Statistics\n",
            "5. 📍 Location Analysis\n",
            "6. ⚠️ High-Risk Analysis\n",
            "7. 🚗 Vehicle Analysis\n",
            "8. 📈 Dashboard\n",
            "9. 🚪 Exit\n",
            "=================================================================\n",
            "Enter your choice (1-9): 2\n",
            "\n",
            "==================================================\n",
            "             ADD VIOLATION\n",
            "==================================================\n",
            "Enter vehicle number: DL01AB1234\n",
            "Enter location: Delhi\n",
            "\n",
            "Violation Types:\n",
            "1. No Helmet\n",
            "2. No Seat Belt\n",
            "3. Overspeeding\n",
            "4. Red Light Jump\n",
            "5. Drunk Driving\n",
            "6. Wrong Parking\n",
            "Select violation type (1-6): 4\n",
            "Enter date (DD-MM-YYYY) or press Enter for today: 01-08-2026\n",
            "\n",
            "Violation added successfully! ✅\n",
            "Vehicle : DL01AB1234\n",
            "Violation: Red Light Jump\n",
            "Fine    : ₹ 5000\n",
            "\n",
            "\n",
            "=================================================================\n",
            "             🚦 TRAFFIC VIOLATION ANALYZER\n",
            "=================================================================\n",
            "1. 📋 Display All Violations\n",
            "2. ➕ Add New Violation\n",
            "3. 🔎 Search Vehicle\n",
            "4. 📊 Violation Statistics\n",
            "5. 📍 Location Analysis\n",
            "6. ⚠️ High-Risk Analysis\n",
            "7. 🚗 Vehicle Analysis\n",
            "8. 📈 Dashboard\n",
            "9. 🚪 Exit\n",
            "=================================================================\n",
            "Enter your choice (1-9): 9\n",
            "\n",
            "Thank you for using Traffic Violation Analyzer! 🚦\n",
            "Project completed successfully.\n"
          ]
        }
      ],
      "source": [
        "# ============================================================\n",
        "#              TRAFFIC VIOLATION ANALYZER\n",
        "#                 Python Minor Project\n",
        "# ============================================================\n",
        "\n",
        "from datetime import datetime\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# SAMPLE TRAFFIC DATA\n",
        "# ============================================================\n",
        "\n",
        "violations = [\n",
        "    {\n",
        "        \"vehicle\": \"DL01AB1234\",\n",
        "        \"location\": \"Delhi\",\n",
        "        \"violation\": \"No Helmet\",\n",
        "        \"date\": \"01-08-2026\",\n",
        "        \"fine\": 1000\n",
        "    },\n",
        "    {\n",
        "        \"vehicle\": \"DL02CD5678\",\n",
        "        \"location\": \"Noida\",\n",
        "        \"violation\": \"Red Light Jump\",\n",
        "        \"date\": \"02-08-2026\",\n",
        "        \"fine\": 5000\n",
        "    },\n",
        "    {\n",
        "        \"vehicle\": \"DL03EF9012\",\n",
        "        \"location\": \"Delhi\",\n",
        "        \"violation\": \"Overspeeding\",\n",
        "        \"date\": \"03-08-2026\",\n",
        "        \"fine\": 2000\n",
        "    },\n",
        "    {\n",
        "        \"vehicle\": \"UP16GH3456\",\n",
        "        \"location\": \"Noida\",\n",
        "        \"violation\": \"No Seat Belt\",\n",
        "        \"date\": \"04-08-2026\",\n",
        "        \"fine\": 1000\n",
        "    },\n",
        "    {\n",
        "        \"vehicle\": \"DL04IJ7890\",\n",
        "        \"location\": \"Delhi\",\n",
        "        \"violation\": \"Overspeeding\",\n",
        "        \"date\": \"05-08-2026\",\n",
        "        \"fine\": 2000\n",
        "    },\n",
        "    {\n",
        "        \"vehicle\": \"HR26KL1122\",\n",
        "        \"location\": \"Gurugram\",\n",
        "        \"violation\": \"Drunk Driving\",\n",
        "        \"date\": \"06-08-2026\",\n",
        "        \"fine\": 10000\n",
        "    },\n",
        "    {\n",
        "        \"vehicle\": \"DL05MN3344\",\n",
        "        \"location\": \"Delhi\",\n",
        "        \"violation\": \"No Helmet\",\n",
        "        \"date\": \"07-08-2026\",\n",
        "        \"fine\": 1000\n",
        "    },\n",
        "    {\n",
        "        \"vehicle\": \"UP14OP5566\",\n",
        "        \"location\": \"Noida\",\n",
        "        \"violation\": \"Red Light Jump\",\n",
        "        \"date\": \"08-08-2026\",\n",
        "        \"fine\": 5000\n",
        "    }\n",
        "]\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# DISPLAY ALL RECORDS\n",
        "# ============================================================\n",
        "\n",
        "def display_all_violations():\n",
        "\n",
        "    print(\"\\n\" + \"=\" * 80)\n",
        "    print(\"                  ALL TRAFFIC VIOLATIONS\")\n",
        "    print(\"=\" * 80)\n",
        "\n",
        "    if len(violations) == 0:\n",
        "        print(\"No violation records found.\")\n",
        "        return\n",
        "\n",
        "    for i, record in enumerate(violations, start=1):\n",
        "\n",
        "        print(f\"\\nRecord {i}\")\n",
        "        print(\"-\" * 50)\n",
        "        print(\"Vehicle Number :\", record[\"vehicle\"])\n",
        "        print(\"Location       :\", record[\"location\"])\n",
        "        print(\"Violation      :\", record[\"violation\"])\n",
        "        print(\"Date           :\", record[\"date\"])\n",
        "        print(\"Fine           : ₹\", record[\"fine\"])\n",
        "\n",
        "    print(\"=\" * 80)\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# ADD NEW VIOLATION\n",
        "# ============================================================\n",
        "\n",
        "def add_violation():\n",
        "\n",
        "    print(\"\\n\" + \"=\" * 50)\n",
        "    print(\"             ADD VIOLATION\")\n",
        "    print(\"=\" * 50)\n",
        "\n",
        "    vehicle = input(\"Enter vehicle number: \").strip().upper()\n",
        "\n",
        "    if vehicle == \"\":\n",
        "        print(\"Vehicle number cannot be empty.\")\n",
        "        return\n",
        "\n",
        "    location = input(\"Enter location: \").strip()\n",
        "\n",
        "    if location == \"\":\n",
        "        print(\"Location cannot be empty.\")\n",
        "        return\n",
        "\n",
        "    print(\"\\nViolation Types:\")\n",
        "    print(\"1. No Helmet\")\n",
        "    print(\"2. No Seat Belt\")\n",
        "    print(\"3. Overspeeding\")\n",
        "    print(\"4. Red Light Jump\")\n",
        "    print(\"5. Drunk Driving\")\n",
        "    print(\"6. Wrong Parking\")\n",
        "\n",
        "    choice = input(\"Select violation type (1-6): \").strip()\n",
        "\n",
        "    violation_data = {\n",
        "        \"1\": (\"No Helmet\", 1000),\n",
        "        \"2\": (\"No Seat Belt\", 1000),\n",
        "        \"3\": (\"Overspeeding\", 2000),\n",
        "        \"4\": (\"Red Light Jump\", 5000),\n",
        "        \"5\": (\"Drunk Driving\", 10000),\n",
        "        \"6\": (\"Wrong Parking\", 500)\n",
        "    }\n",
        "\n",
        "    if choice not in violation_data:\n",
        "        print(\"Invalid violation type.\")\n",
        "        return\n",
        "\n",
        "    violation, fine = violation_data[choice]\n",
        "\n",
        "    date_input = input(\n",
        "        \"Enter date (DD-MM-YYYY) or press Enter for today: \"\n",
        "    ).strip()\n",
        "\n",
        "    if date_input == \"\":\n",
        "        date_input = datetime.now().strftime(\"%d-%m-%Y\")\n",
        "    else:\n",
        "        try:\n",
        "            datetime.strptime(date_input, \"%d-%m-%Y\")\n",
        "        except ValueError:\n",
        "            print(\"Invalid date format.\")\n",
        "            return\n",
        "\n",
        "    new_record = {\n",
        "        \"vehicle\": vehicle,\n",
        "        \"location\": location,\n",
        "        \"violation\": violation,\n",
        "        \"date\": date_input,\n",
        "        \"fine\": fine\n",
        "    }\n",
        "\n",
        "    violations.append(new_record)\n",
        "\n",
        "    print(\"\\nViolation added successfully! ✅\")\n",
        "    print(\"Vehicle :\", vehicle)\n",
        "    print(\"Violation:\", violation)\n",
        "    print(\"Fine    : ₹\", fine)\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# SEARCH VEHICLE\n",
        "# ============================================================\n",
        "\n",
        "def search_vehicle():\n",
        "\n",
        "    print(\"\\n\" + \"=\" * 50)\n",
        "    print(\"             SEARCH VEHICLE\")\n",
        "    print(\"=\" * 50)\n",
        "\n",
        "    vehicle = input(\n",
        "        \"Enter vehicle number: \"\n",
        "    ).strip().upper()\n",
        "\n",
        "    found = False\n",
        "    total_fine = 0\n",
        "    count = 0\n",
        "\n",
        "    for record in violations:\n",
        "\n",
        "        if record[\"vehicle\"] == vehicle:\n",
        "\n",
        "            found = True\n",
        "            count += 1\n",
        "            total_fine += record[\"fine\"]\n",
        "\n",
        "            print(\"\\n----------------------------------------\")\n",
        "            print(\"Vehicle  :\", record[\"vehicle\"])\n",
        "            print(\"Location :\", record[\"location\"])\n",
        "            print(\"Violation:\", record[\"violation\"])\n",
        "            print(\"Date     :\", record[\"date\"])\n",
        "            print(\"Fine     : ₹\", record[\"fine\"])\n",
        "\n",
        "    if not found:\n",
        "\n",
        "        print(\"\\nNo violations found for\", vehicle)\n",
        "\n",
        "    else:\n",
        "\n",
        "        print(\"\\n----------------------------------------\")\n",
        "        print(\"Total Violations :\", count)\n",
        "        print(\"Total Fine       : ₹\", total_fine)\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# VIOLATION STATISTICS\n",
        "# ============================================================\n",
        "\n",
        "def violation_statistics():\n",
        "\n",
        "    print(\"\\n\" + \"=\" * 60)\n",
        "    print(\"             VIOLATION STATISTICS\")\n",
        "    print(\"=\" * 60)\n",
        "\n",
        "    if len(violations) == 0:\n",
        "        print(\"No data available.\")\n",
        "        return\n",
        "\n",
        "    violation_count = {}\n",
        "    total_fine = 0\n",
        "\n",
        "    for record in violations:\n",
        "\n",
        "        violation = record[\"violation\"]\n",
        "\n",
        "        if violation not in violation_count:\n",
        "            violation_count[violation] = 0\n",
        "\n",
        "        violation_count[violation] += 1\n",
        "        total_fine += record[\"fine\"]\n",
        "\n",
        "    print(\"\\nViolation Frequency:\")\n",
        "    print(\"-\" * 40)\n",
        "\n",
        "    for violation, count in violation_count.items():\n",
        "\n",
        "        print(\n",
        "            f\"{violation:<20} : {count}\"\n",
        "        )\n",
        "\n",
        "    most_common = max(\n",
        "        violation_count,\n",
        "        key=violation_count.get\n",
        "    )\n",
        "\n",
        "    print(\"\\nMost Common Violation:\")\n",
        "    print(most_common)\n",
        "\n",
        "    print(\"\\nTotal Violations:\", len(violations))\n",
        "    print(\"Total Fine Collected: ₹\", total_fine)\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# LOCATION ANALYSIS\n",
        "# ============================================================\n",
        "\n",
        "def location_analysis():\n",
        "\n",
        "    print(\"\\n\" + \"=\" * 60)\n",
        "    print(\"               LOCATION ANALYSIS\")\n",
        "    print(\"=\" * 60)\n",
        "\n",
        "    location_count = {}\n",
        "\n",
        "    for record in violations:\n",
        "\n",
        "        location = record[\"location\"]\n",
        "\n",
        "        if location not in location_count:\n",
        "            location_count[location] = 0\n",
        "\n",
        "        location_count[location] += 1\n",
        "\n",
        "    for location, count in location_count.items():\n",
        "\n",
        "        print(\n",
        "            f\"{location:<20} : {count} violations\"\n",
        "        )\n",
        "\n",
        "    if location_count:\n",
        "\n",
        "        highest_location = max(\n",
        "            location_count,\n",
        "            key=location_count.get\n",
        "        )\n",
        "\n",
        "        print(\"\\nHighest Violation Location:\")\n",
        "        print(highest_location)\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# HIGH-RISK VIOLATION ANALYSIS\n",
        "# ============================================================\n",
        "\n",
        "def high_risk_analysis():\n",
        "\n",
        "    print(\"\\n\" + \"=\" * 60)\n",
        "    print(\"             HIGH-RISK ANALYSIS\")\n",
        "    print(\"=\" * 60)\n",
        "\n",
        "    high_risk = [\n",
        "        \"Drunk Driving\",\n",
        "        \"Red Light Jump\",\n",
        "        \"Overspeeding\"\n",
        "    ]\n",
        "\n",
        "    found = False\n",
        "\n",
        "    for record in violations:\n",
        "\n",
        "        if record[\"violation\"] in high_risk:\n",
        "\n",
        "            found = True\n",
        "\n",
        "            print(\"\\n⚠️ HIGH-RISK VIOLATION\")\n",
        "            print(\"-\" * 40)\n",
        "            print(\"Vehicle  :\", record[\"vehicle\"])\n",
        "            print(\"Location :\", record[\"location\"])\n",
        "            print(\"Violation:\", record[\"violation\"])\n",
        "            print(\"Date     :\", record[\"date\"])\n",
        "            print(\"Fine     : ₹\", record[\"fine\"])\n",
        "\n",
        "    if not found:\n",
        "\n",
        "        print(\"No high-risk violations found.\")\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# TOP OFFENDING VEHICLES\n",
        "# ============================================================\n",
        "\n",
        "def vehicle_analysis():\n",
        "\n",
        "    print(\"\\n\" + \"=\" * 60)\n",
        "    print(\"              VEHICLE ANALYSIS\")\n",
        "    print(\"=\" * 60)\n",
        "\n",
        "    vehicle_count = {}\n",
        "\n",
        "    for record in violations:\n",
        "\n",
        "        vehicle = record[\"vehicle\"]\n",
        "\n",
        "        if vehicle not in vehicle_count:\n",
        "            vehicle_count[vehicle] = 0\n",
        "\n",
        "        vehicle_count[vehicle] += 1\n",
        "\n",
        "    sorted_vehicles = sorted(\n",
        "        vehicle_count.items(),\n",
        "        key=lambda x: x[1],\n",
        "        reverse=True\n",
        "    )\n",
        "\n",
        "    print(\"\\nVehicles by Number of Violations:\")\n",
        "    print(\"-\" * 45)\n",
        "\n",
        "    for vehicle, count in sorted_vehicles:\n",
        "\n",
        "        print(\n",
        "            f\"{vehicle:<15} : {count} violation(s)\"\n",
        "        )\n",
        "\n",
        "    if sorted_vehicles:\n",
        "\n",
        "        top_vehicle = sorted_vehicles[0]\n",
        "\n",
        "        print(\"\\n🚨 Most Frequently Violating Vehicle:\")\n",
        "        print(\"Vehicle :\", top_vehicle[0])\n",
        "        print(\"Violations :\", top_vehicle[1])\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# DASHBOARD\n",
        "# ============================================================\n",
        "\n",
        "def dashboard():\n",
        "\n",
        "    print(\"\\n\")\n",
        "    print(\"=\" * 70)\n",
        "    print(\"             🚦 TRAFFIC VIOLATION DASHBOARD\")\n",
        "    print(\"=\" * 70)\n",
        "\n",
        "    total_violations = len(violations)\n",
        "\n",
        "    total_fine = sum(\n",
        "        record[\"fine\"] for record in violations\n",
        "    )\n",
        "\n",
        "    high_risk_count = 0\n",
        "\n",
        "    for record in violations:\n",
        "\n",
        "        if record[\"violation\"] in [\n",
        "            \"Drunk Driving\",\n",
        "            \"Red Light Jump\",\n",
        "            \"Overspeeding\"\n",
        "        ]:\n",
        "            high_risk_count += 1\n",
        "\n",
        "    unique_vehicles = set(\n",
        "        record[\"vehicle\"] for record in violations\n",
        "    )\n",
        "\n",
        "    print(\"\\n📊 SUMMARY\")\n",
        "    print(\"-\" * 50)\n",
        "\n",
        "    print(\"Total Violations :\", total_violations)\n",
        "    print(\"Unique Vehicles  :\", len(unique_vehicles))\n",
        "    print(\"Total Fine       : ₹\", total_fine)\n",
        "    print(\"High-Risk Cases  :\", high_risk_count)\n",
        "\n",
        "    if total_violations > 0:\n",
        "\n",
        "        average_fine = total_fine / total_violations\n",
        "\n",
        "        print(\n",
        "            \"Average Fine     : ₹\",\n",
        "            round(average_fine, 2)\n",
        "        )\n",
        "\n",
        "    print(\"=\" * 70)\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# MAIN MENU\n",
        "# ============================================================\n",
        "\n",
        "def main():\n",
        "\n",
        "    while True:\n",
        "\n",
        "        print(\"\\n\")\n",
        "        print(\"=\" * 65)\n",
        "        print(\"             🚦 TRAFFIC VIOLATION ANALYZER\")\n",
        "        print(\"=\" * 65)\n",
        "\n",
        "        print(\"1. 📋 Display All Violations\")\n",
        "        print(\"2. ➕ Add New Violation\")\n",
        "        print(\"3. 🔎 Search Vehicle\")\n",
        "        print(\"4. 📊 Violation Statistics\")\n",
        "        print(\"5. 📍 Location Analysis\")\n",
        "        print(\"6. ⚠️ High-Risk Analysis\")\n",
        "        print(\"7. 🚗 Vehicle Analysis\")\n",
        "        print(\"8. 📈 Dashboard\")\n",
        "        print(\"9. 🚪 Exit\")\n",
        "\n",
        "        print(\"=\" * 65)\n",
        "\n",
        "        choice = input(\n",
        "            \"Enter your choice (1-9): \"\n",
        "        ).strip()\n",
        "\n",
        "        if choice == \"1\":\n",
        "\n",
        "            display_all_violations()\n",
        "\n",
        "        elif choice == \"2\":\n",
        "\n",
        "            add_violation()\n",
        "\n",
        "        elif choice == \"3\":\n",
        "\n",
        "            search_vehicle()\n",
        "\n",
        "        elif choice == \"4\":\n",
        "\n",
        "            violation_statistics()\n",
        "\n",
        "        elif choice == \"5\":\n",
        "\n",
        "            location_analysis()\n",
        "\n",
        "        elif choice == \"6\":\n",
        "\n",
        "            high_risk_analysis()\n",
        "\n",
        "        elif choice == \"7\":\n",
        "\n",
        "            vehicle_analysis()\n",
        "\n",
        "        elif choice == \"8\":\n",
        "\n",
        "            dashboard()\n",
        "\n",
        "        elif choice == \"9\":\n",
        "\n",
        "            print(\"\\nThank you for using Traffic Violation Analyzer! 🚦\")\n",
        "            print(\"Project completed successfully.\")\n",
        "            break\n",
        "\n",
        "        else:\n",
        "\n",
        "            print(\n",
        "                \"\\n❌ Invalid choice.\"\n",
        "                \"\\nPlease enter a number between 1 and 9.\"\n",
        "            )\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# RUN PROJECT\n",
        "# ============================================================\n",
        "\n",
        "main()"
      ]
    }
  ]
}
