{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "execution_count": 1,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "HgMCqkxHCZwf",
        "outputId": "b6fa25ce-03e4-4f8b-9e0f-4405bab7649d"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\n",
            "==========================================\n",
            "       FOOD MOOD RECOMMENDATION SYSTEM\n",
            "==========================================\n",
            "1. Get Food Recommendation\n",
            "2. View All Food Items\n",
            "3. Exit\n",
            "==========================================\n",
            "Enter your choice (1-3): 2\n",
            "\n",
            "========== ALL FOOD ITEMS ==========\n",
            "\n",
            "------------------------------\n",
            "Food Name : Cheese Pizza\n",
            "Price     : ₹ 250\n",
            "Type      : Veg\n",
            "Cuisine   : Italian\n",
            "------------------------------\n",
            "\n",
            "------------------------------\n",
            "Food Name : Chicken Biryani\n",
            "Price     : ₹ 220\n",
            "Type      : Non-Veg\n",
            "Cuisine   : Indian\n",
            "------------------------------\n",
            "\n",
            "------------------------------\n",
            "Food Name : Paneer Butter Masala\n",
            "Price     : ₹ 200\n",
            "Type      : Veg\n",
            "Cuisine   : Indian\n",
            "------------------------------\n",
            "\n",
            "------------------------------\n",
            "Food Name : Chocolate Cake\n",
            "Price     : ₹ 180\n",
            "Type      : Veg\n",
            "Cuisine   : Dessert\n",
            "------------------------------\n",
            "\n",
            "------------------------------\n",
            "Food Name : French Fries\n",
            "Price     : ₹ 120\n",
            "Type      : Veg\n",
            "Cuisine   : Fast Food\n",
            "------------------------------\n",
            "\n",
            "------------------------------\n",
            "Food Name : Veg Burger\n",
            "Price     : ₹ 150\n",
            "Type      : Veg\n",
            "Cuisine   : Fast Food\n",
            "------------------------------\n",
            "\n",
            "------------------------------\n",
            "Food Name : Ice Cream\n",
            "Price     : ₹ 100\n",
            "Type      : Veg\n",
            "Cuisine   : Dessert\n",
            "------------------------------\n",
            "\n",
            "------------------------------\n",
            "Food Name : Masala Dosa\n",
            "Price     : ₹ 140\n",
            "Type      : Veg\n",
            "Cuisine   : South Indian\n",
            "------------------------------\n",
            "\n",
            "------------------------------\n",
            "Food Name : Pasta\n",
            "Price     : ₹ 190\n",
            "Type      : Veg\n",
            "Cuisine   : Italian\n",
            "------------------------------\n",
            "\n",
            "------------------------------\n",
            "Food Name : Chicken Roll\n",
            "Price     : ₹ 160\n",
            "Type      : Non-Veg\n",
            "Cuisine   : Fast Food\n",
            "------------------------------\n",
            "\n",
            "==========================================\n",
            "       FOOD MOOD RECOMMENDATION SYSTEM\n",
            "==========================================\n",
            "1. Get Food Recommendation\n",
            "2. View All Food Items\n",
            "3. Exit\n",
            "==========================================\n",
            "Enter your choice (1-3): 1\n",
            "\n",
            "========== FOOD RECOMMENDATION ==========\n",
            "How are you feeling? (happy/sad/hungry/excited/relaxed/bored): bored\n",
            "Do you want Veg or Non-Veg? (Veg/Non-Veg): veg\n",
            "Enter your maximum budget (₹): 150\n",
            "\n",
            "========== RECOMMENDED FOOD ==========\n",
            "Here are some foods for you:\n",
            "\n",
            "------------------------------\n",
            "Food Name : French Fries\n",
            "Price     : ₹ 120\n",
            "Type      : Veg\n",
            "Cuisine   : Fast Food\n",
            "------------------------------\n",
            "\n",
            "------------------------------\n",
            "Food Name : Veg Burger\n",
            "Price     : ₹ 150\n",
            "Type      : Veg\n",
            "Cuisine   : Fast Food\n",
            "------------------------------\n",
            "\n",
            "==========================================\n",
            "       FOOD MOOD RECOMMENDATION SYSTEM\n",
            "==========================================\n",
            "1. Get Food Recommendation\n",
            "2. View All Food Items\n",
            "3. Exit\n",
            "==========================================\n",
            "Enter your choice (1-3): 3\n",
            "\n",
            "Thank you for using Food Mood Recommendation System!\n"
          ]
        }
      ],
      "source": [
        "# ============================================================\n",
        "#          FOOD MOOD RECOMMENDATION SYSTEM\n",
        "# ============================================================\n",
        "\n",
        "foods = [\n",
        "    {\n",
        "        \"name\": \"Cheese Pizza\",\n",
        "        \"price\": 250,\n",
        "        \"type\": \"Veg\",\n",
        "        \"cuisine\": \"Italian\",\n",
        "        \"moods\": [\"happy\", \"excited\", \"bored\"]\n",
        "    },\n",
        "    {\n",
        "        \"name\": \"Chicken Biryani\",\n",
        "        \"price\": 220,\n",
        "        \"type\": \"Non-Veg\",\n",
        "        \"cuisine\": \"Indian\",\n",
        "        \"moods\": [\"happy\", \"hungry\", \"excited\"]\n",
        "    },\n",
        "    {\n",
        "        \"name\": \"Paneer Butter Masala\",\n",
        "        \"price\": 200,\n",
        "        \"type\": \"Veg\",\n",
        "        \"cuisine\": \"Indian\",\n",
        "        \"moods\": [\"happy\", \"relaxed\", \"hungry\"]\n",
        "    },\n",
        "    {\n",
        "        \"name\": \"Chocolate Cake\",\n",
        "        \"price\": 180,\n",
        "        \"type\": \"Veg\",\n",
        "        \"cuisine\": \"Dessert\",\n",
        "        \"moods\": [\"sad\", \"happy\", \"bored\"]\n",
        "    },\n",
        "    {\n",
        "        \"name\": \"French Fries\",\n",
        "        \"price\": 120,\n",
        "        \"type\": \"Veg\",\n",
        "        \"cuisine\": \"Fast Food\",\n",
        "        \"moods\": [\"bored\", \"happy\", \"excited\"]\n",
        "    },\n",
        "    {\n",
        "        \"name\": \"Veg Burger\",\n",
        "        \"price\": 150,\n",
        "        \"type\": \"Veg\",\n",
        "        \"cuisine\": \"Fast Food\",\n",
        "        \"moods\": [\"hungry\", \"happy\", \"bored\"]\n",
        "    },\n",
        "    {\n",
        "        \"name\": \"Ice Cream\",\n",
        "        \"price\": 100,\n",
        "        \"type\": \"Veg\",\n",
        "        \"cuisine\": \"Dessert\",\n",
        "        \"moods\": [\"sad\", \"happy\", \"relaxed\"]\n",
        "    },\n",
        "    {\n",
        "        \"name\": \"Masala Dosa\",\n",
        "        \"price\": 140,\n",
        "        \"type\": \"Veg\",\n",
        "        \"cuisine\": \"South Indian\",\n",
        "        \"moods\": [\"hungry\", \"relaxed\", \"happy\"]\n",
        "    },\n",
        "    {\n",
        "        \"name\": \"Pasta\",\n",
        "        \"price\": 190,\n",
        "        \"type\": \"Veg\",\n",
        "        \"cuisine\": \"Italian\",\n",
        "        \"moods\": [\"relaxed\", \"happy\", \"bored\"]\n",
        "    },\n",
        "    {\n",
        "        \"name\": \"Chicken Roll\",\n",
        "        \"price\": 160,\n",
        "        \"type\": \"Non-Veg\",\n",
        "        \"cuisine\": \"Fast Food\",\n",
        "        \"moods\": [\"hungry\", \"excited\", \"happy\"]\n",
        "    }\n",
        "]\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# DISPLAY FOOD\n",
        "# ============================================================\n",
        "\n",
        "def display_food(food):\n",
        "    print(\"\\n------------------------------\")\n",
        "    print(\"Food Name :\", food[\"name\"])\n",
        "    print(\"Price     :\", \"₹\", food[\"price\"])\n",
        "    print(\"Type      :\", food[\"type\"])\n",
        "    print(\"Cuisine   :\", food[\"cuisine\"])\n",
        "    print(\"------------------------------\")\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# RECOMMEND FOOD\n",
        "# ============================================================\n",
        "\n",
        "def recommend_food():\n",
        "    print(\"\\n========== FOOD RECOMMENDATION ==========\")\n",
        "\n",
        "    mood = input(\n",
        "        \"How are you feeling? \"\n",
        "        \"(happy/sad/hungry/excited/relaxed/bored): \"\n",
        "    ).strip().lower()\n",
        "\n",
        "    food_type = input(\n",
        "        \"Do you want Veg or Non-Veg? \"\n",
        "        \"(Veg/Non-Veg): \"\n",
        "    ).strip().lower()\n",
        "\n",
        "    try:\n",
        "        budget = float(input(\"Enter your maximum budget (₹): \"))\n",
        "    except ValueError:\n",
        "        print(\"Please enter a valid budget!\")\n",
        "        return\n",
        "\n",
        "    recommendations = []\n",
        "\n",
        "    for food in foods:\n",
        "\n",
        "        mood_match = mood in food[\"moods\"]\n",
        "        type_match = food[\"type\"].lower() == food_type\n",
        "        budget_match = food[\"price\"] <= budget\n",
        "\n",
        "        if mood_match and type_match and budget_match:\n",
        "            recommendations.append(food)\n",
        "\n",
        "    print(\"\\n========== RECOMMENDED FOOD ==========\")\n",
        "\n",
        "    if len(recommendations) == 0:\n",
        "        print(\"Sorry! No food found matching your choices.\")\n",
        "        print(\"Try changing your mood, food type, or budget.\")\n",
        "    else:\n",
        "        print(\"Here are some foods for you:\")\n",
        "\n",
        "        for food in recommendations:\n",
        "            display_food(food)\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# VIEW ALL FOOD\n",
        "# ============================================================\n",
        "\n",
        "def view_all_food():\n",
        "    print(\"\\n========== ALL FOOD ITEMS ==========\")\n",
        "\n",
        "    for food in foods:\n",
        "        display_food(food)\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# MAIN MENU\n",
        "# ============================================================\n",
        "\n",
        "def main():\n",
        "\n",
        "    while True:\n",
        "\n",
        "        print(\"\\n==========================================\")\n",
        "        print(\"       FOOD MOOD RECOMMENDATION SYSTEM\")\n",
        "        print(\"==========================================\")\n",
        "        print(\"1. Get Food Recommendation\")\n",
        "        print(\"2. View All Food Items\")\n",
        "        print(\"3. Exit\")\n",
        "        print(\"==========================================\")\n",
        "\n",
        "        choice = input(\"Enter your choice (1-3): \").strip()\n",
        "\n",
        "        if choice == \"1\":\n",
        "            recommend_food()\n",
        "\n",
        "        elif choice == \"2\":\n",
        "            view_all_food()\n",
        "\n",
        "        elif choice == \"3\":\n",
        "            print(\"\\nThank you for using Food Mood Recommendation System!\")\n",
        "            break\n",
        "\n",
        "        else:\n",
        "            print(\"Invalid choice! Please enter 1, 2, or 3.\")\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# START PROGRAM\n",
        "# ============================================================\n",
        "\n",
        "main()"
      ]
    }
  ]
}
