{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "execution_count": 1,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "V-acc8wL5t8e",
        "outputId": "a209d76d-5dfb-4a11-8ec1-76e60083b2a2"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Welcome to Tic-Tac-Toe!\n",
            "\n",
            " 1 | 2 | 3 \n",
            "---|---|---\n",
            " 4 | 5 | 6 \n",
            "---|---|---\n",
            " 7 | 8 | 9 \n",
            "\n",
            "Player X, enter a slot (1-9): 8\n",
            "\n",
            " 1 | 2 | 3 \n",
            "---|---|---\n",
            " 4 | 5 | 6 \n",
            "---|---|---\n",
            " 7 | X | 9 \n",
            "\n",
            "Player O, enter a slot (1-9): 5\n",
            "\n",
            " 1 | 2 | 3 \n",
            "---|---|---\n",
            " 4 | O | 6 \n",
            "---|---|---\n",
            " 7 | X | 9 \n",
            "\n",
            "Player X, enter a slot (1-9): 9\n",
            "\n",
            " 1 | 2 | 3 \n",
            "---|---|---\n",
            " 4 | O | 6 \n",
            "---|---|---\n",
            " 7 | X | X \n",
            "\n",
            "Player O, enter a slot (1-9): 1\n",
            "\n",
            " O | 2 | 3 \n",
            "---|---|---\n",
            " 4 | O | 6 \n",
            "---|---|---\n",
            " 7 | X | X \n",
            "\n",
            "Player X, enter a slot (1-9): 7\n",
            "\n",
            " O | 2 | 3 \n",
            "---|---|---\n",
            " 4 | O | 6 \n",
            "---|---|---\n",
            " X | X | X \n",
            "\n",
            "Congratulations! Player X wins!\n"
          ]
        }
      ],
      "source": [
        "def print_board(board):\n",
        "    \"\"\"Prints the current game board matrix.\"\"\"\n",
        "    print(f\"\\n {board[0]} | {board[1]} | {board[2]} \")\n",
        "    print(\"---|---|---\")\n",
        "    print(f\" {board[3]} | {board[4]} | {board[5]} \")\n",
        "    print(\"---|---|---\")\n",
        "    print(f\" {board[6]} | {board[7]} | {board[8]} \\n\")\n",
        "\n",
        "def check_winner(board, player):\n",
        "    \"\"\"Checks if the specified player has won the match.\"\"\"\n",
        "    win_conditions = [\n",
        "        [0, 1, 2], [3, 4, 5], [6, 7, 8], # Horizontal rows\n",
        "        [0, 3, 6], [1, 4, 7], [2, 5, 8], # Vertical columns\n",
        "        [0, 4, 8], [2, 4, 6]             # Diagonal rows\n",
        "    ]\n",
        "    return any(all(board[cell] == player for cell in condition) for condition in win_conditions)\n",
        "\n",
        "def is_board_full(board):\n",
        "    \"\"\"Validates if there are no remaining empty slots on the board.\"\"\"\n",
        "    return all(cell in ['X', 'O'] for cell in board)\n",
        "\n",
        "def tic_tac_toe():\n",
        "    \"\"\"Main function running the game loop framework.\"\"\"\n",
        "    # Initialize board with position numbers 1 through 9\n",
        "    board = [str(i) for i in range(1, 10)]\n",
        "    current_player = 'X'\n",
        "\n",
        "    print(\"Welcome to Tic-Tac-Toe!\")\n",
        "\n",
        "    while True:\n",
        "        print_board(board)\n",
        "\n",
        "        # Capture and validate player move choice\n",
        "        try:\n",
        "            choice = int(input(f\"Player {current_player}, enter a slot (1-9): \")) - 1\n",
        "            if choice < 0 or choice > 8 or board[choice] in ['X', 'O']:\n",
        "                print(\"Invalid or occupied slot! Please pick another.\")\n",
        "                continue\n",
        "        except ValueError:\n",
        "            print(\"Please enter a valid number between 1 and 9.\")\n",
        "            continue\n",
        "\n",
        "        # Place player's symbol\n",
        "        board[choice] = current_player\n",
        "\n",
        "        # Check for game-ending conditions\n",
        "        if check_winner(board, current_player):\n",
        "            print_board(board)\n",
        "            print(f\"Congratulations! Player {current_player} wins!\")\n",
        "            break\n",
        "\n",
        "        if is_board_full(board):\n",
        "            print_board(board)\n",
        "            print(\"It's a tie game!\")\n",
        "            break\n",
        "\n",
        "        # Alternate turn to the next player\n",
        "        current_player = 'O' if current_player == 'X' else 'X'\n",
        "\n",
        "if __name__ == \"__main__\":\n",
        "    tic_tac_toe()\n"
      ]
    }
  ]
}
